# Generated by Django 4.2.7 on 2023-11-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0003_alter_review_body_alter_review_headline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.CharField(max_length=8192, verbose_name="Commentaire"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(max_length=2048, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(default=set, upload_to="", verbose_name="Image"),
            preserve_default=False,
        ),
    ]
