# Generated by Django 4.2.7 on 2023-12-04 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0004_alter_review_body_alter_ticket_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollows",
        ),
    ]
